### ISSUE TITLE
issue setup

### ISSUE THREAD

**Issue by lightrain125** [3s3s/opentrade#84]
Hello, i setup but error.

root@vultr:~# cd  ~/opentrade/server
root@vultr:~/opentrade/server# sudo node main.js
sudo: node: command not found
root@vultr:~/opentrade/server#   

Please help me. thanks

**Comment by jonn4y** [comment]
What steps have you taken to get this far, what is the full error you are getting?

Have you installed node first in the opentrade dir?

**Comment by lightrain125** [comment]
i complete step

udo apt-get update
sudo apt-get install build-essential libssl-dev curl -y
curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh -o install_nvm.sh
bash install_nvm.sh
sudo reboot

nvm install 6.0.0

git clone https://github.com/3s3s/opentrade.git
cd opentrade

sudo npm install 

mkdir ~/opentrade/server/database

**Comment by lightrain125** [comment]
I have not installed the first node.

**Comment by 3s3s** [comment]
Hi
you can try "nodejs main.js" instead, but VULTR is bad provider for OpenTrade anyway... Vultr is blocking outgoing SMTP connections so OpenTrade will not to send emails and it will be impossible to complete registration

**Comment by lightrain125** [comment]
hi, full error 
module.js:549
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/opentrade/server/main.js:8:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by Tr0j4n9** [comment]
Try re-cloning with a new update. If that does not work, contact me on my Discord: https://discord.gg/fEYMcvX

**Comment by cryptonana** [comment]
dont use sudo without sudo run command node main.js and if you see these errors

/root/opentrade/node_modules/sendmail/sendmail.js:1
(function (exports, require, module, __filename, __dirname) { const {createConnection} = require('net');
^

SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/root/opentrade/server/modules/mailer.js:4:18)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

run command
killall node

and after run 
nohup node main.js &

go browser

**Comment by diakas** [comment]
neded nvm install 8.0 - 8.12
